#!/usr/bin/env php
<?php
use OsmScripts\Core\Hints\ComposerLockHint;

call_user_func(function () {
    global $argv;

    $name = basename(__FILE__);
    if (!is_file('composer.lock') || !($contents = file_get_contents('composer.lock'))) {
        throw new Exception("'composer.lock' not found");
    }

    /* @var ComposerLockHint $json */
    if (!($json = json_decode($contents))) {
        throw new Exception("'composer.lock' is not valid JSON file");
    }

    $args = implode(' ', array_slice($argv, 1));
    if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
        if (file_exists("vendor\\bin\\{$name}.bat")) {
            echo "vendor\\bin\\{$name}.bat $args 2>&1\n";
            passthru("vendor\\bin\\{$name}.bat $args 2>&1", $exitCode);
            exit($exitCode);
        }
    }
    else {
        if (file_exists("vendor/bin/{$name}")) {
            passthru("vendor/bin/{$name} $args 2>&1", $exitCode);
            exit($exitCode);
        }
    }

    throw new Exception("Script '$name' is not found in '" . getcwd() . "'");
});